# Generated by Django 3.1.1 on 2020-09-26 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='activity_periods',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
