# Generated by Django 3.1.1 on 2020-09-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200926_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPeriod',
            new_name='Activity',
        ),
    ]
